language: android
jdk: oraclejdk7
sudo: false

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository

script: ./gradlew testRelease
